services:
  socks5:
    build: .
    image: microsocks-proxy:latest
    container_name: microsocks-proxy
    ports:
      - "1080:1080"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    restart: unless-stopped
